# Generated by Django 3.0.5 on 2020-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='possui_estoque',
            field=models.BooleanField(default=False, verbose_name='Tem no estoque'),
        ),
    ]
