# Generated by Django 3.0.5 on 2020-06-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_possui_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': (('change_estoque', 'Alterar produto no estoque'),)},
        ),
    ]
